apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed-deployment
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmed-api
        image: leonardosartorello/vollmed:v8
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_HOST
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_DATABASE
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vallmed-secrets
              key: DB_PASSWORD
